default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  username: myuser
  password: mypass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: interviewTest_development


test:
  <<: *default
  database: interviewTest_test


production:
  <<: *default
  database: interviewTest_production
  username: interviewTest
  password: <%= ENV["INTERVIEWTEST_DATABASE_PASSWORD"] %>
